use_frameworks!

platform :ios, '8.0'

target 'podExample_Example' do
  pod 'podExample', :path => '../'

  target 'podExample_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
